### PR TITLE
Migrate to Astro (#49)

### LINKED ISSUE #49: Migrate to Astro
Hi there! I'm an Astro maintainer and I can help you migrate (following https://twitter.com/yagiznizipli/status/1734703162106224784)! Just creating this issue to track the progress

TODO
- [x] Report Astro Compiler issue
- [x] `[slug]`
	- [x] add missing components
	- [x] opengraph
	- [x] add image to head
- [x] Refactor SEO
- [x] markdown plugins
- [x] Catch up with latest commits on `main`
- [x] improve content (eg image)
- [x] rework Figure to use ImageMetadata
- [x] remove type from content entries
- [x] replace any img by Image
- [x] improve components (migrate to Astro if possible)
- [x] use adapted client directives
- [x] Setup Sentry
- [x] Update CLI
- [x] Check all routes
- [ ] Check SEO
- [x] Check TODOs
- [x] a11y audits
- [ ] Check Lighthouse
- [x] Check regressions
- [x] Check for missing repo files
- [x] README
- [x] Move from `temp` to root

### PR DESCRIPTION
**Pull request by florian-lefebvre**
TODO (see issue)

### CODE REVIEW

**Comment by anonrig** [comment]
Awesome work @florian-lefebvre. Can you share a todo list to merge this?

**Comment by florian-lefebvre** [comment]
Sure! I was keeping it in my notepad but I'm going to share it here

**Comment by anonrig** [comment]
@florian-lefebvre Can we keep the content folder in the root?

**Comment by florian-lefebvre** [comment]
No unfortunately if you want (you should!) to take advantage of [Content Collections](https://docs.astro.build/en/guides/content-collections/#_top). It has to live under `src/content`

**Comment by anonrig** [comment]
I changed the base to `astro-rewrite`, and I'm merging it 👍

**Pull request merged**
